configure.ac
Added missing QT4 dependency and corrected new line in version parsing
=> Added Missing Dependency in Configure

lib/rdevent_line.cpp
Let's say you have the following in a clock:
03:00:00 Play New Music Sweeper
03:00:10 Play Sched Code "NewMusic"
When generating the log, due to artist/title separation rules, there isn't a song available with the "NewMusic" Sched Code. What happens now is a song from another Sched Code, such as "70s", is picked at random. We now have a new music sweeper playing into a 70s song.
It would be better to pick another new music song that violates the artist/title rules than a song that violates the sched code rules.
We used to have a "holiday" sched code. We had to move holiday out of the "Music" group into a "Holiday" group to make sure a Christmas song doesn't play in August due to a artist/title failure.
This change moves the schedule code deconflicting rules before the article/title rules, …
=> Prioritize scheduler code over artist/title separation

ChangeLog, rdcatchd/rdcatchd.cpp, rdservice/startup.cpp
* Fixed a regression in rdcatchd(1) to change location
of rdcatchd(1) from 'bin/rdcatchd' to 'sbin/rdcatchd'.
* Fixed a regression in rdservice(8) by removing quotation marks
from rdimport(1) '--add-scheduler-code' argument that broke
=> 2018-08-25 Patrick Linstruth <patrick@deltecent.com>

ChangeLog, docs/rivwebcapi/rd_listgroups.xml
Madde changes to ChangeLog and rd_listgroups.xml to explicitly state rd_listgroups returns user's groups.
=> Fixed documentation rd_listgroups

ChangeLog, docs/opsguide/rml.xml, lib/rdlistviewitem.cpp, lib/rdlistviewitem.h, lib/rdsimpleplayer.cpp, lib/rdsimpleplayer.h, rdlibrary/edit_cart.cpp, rdlibrary/lib_listview.cpp, rdlibrary/rdlibrary.cpp, rdlibrary/rdlibrary.h
Ability to expand carts and view individual cuts.
Ability to play carts/cuts directly from the list view.
=> (Master New Features) RDLibrary Improvements

ChangeLog, rdservice/maint_routines.cpp
I think this change was lost in the shuffle.
=> (Master Bug Fix) Fixed bug where wrong ID was used for local maintenance

ChangeLog, lib/rdripc.cpp, rdlibrary/macro_cart.cpp, rdlibrary/macro_cart.h, rdlibrary/rdlibrary_cs.ts, rdlibrary/rdlibrary_de.ts, rdlibrary/rdlibrary_es.ts, rdlibrary/rdlibrary_fr.ts, rdlibrary/rdlibrary_nb.ts, rdlibrary/rdlibrary_nn.ts, rdlibrary/rdlibrary_pt_BR.ts
Also improves button management and permissions
=> (Master Bug Fix) Update macro editor in rdlibrary(1) to fix display of "--- End of cart ---"

ChangeLog, docs/tables/cart_sched_codes.txt, lib/dbversion.h, lib/rdcart.cpp, lib/rdcart_dialog.cpp, lib/rdcart_search_text.cpp, lib/rdcut_dialog.cpp, lib/rdevent_line.cpp, rdlibrary/list_reports.cpp, rdlibrary/rdlibrary.cpp, rdlogmanager/edit_event.cpp, utils/rddbmgr/revertschema.cpp, utils/rddbmgr/schemamap.cpp, utils/rddbmgr/updateschema.cpp, web/rdxport/carts.cpp
This was a fairly intrusive change. Some help with additional testing is necessary.
I also think it does slow down log generation. There's probably an optimization out there.
=> (Master) Move 'CART.SCHED_CODES' field to 'CART_SCHED_CODES' table.

ChangeLog, lib/rdlogplay.cpp
=> (Master Regression) Fixed regression where remote log changes did not auto refresh

ChangeLog, docs/opsguide/frontspiece.xml.in, docs/opsguide/gpio_switcher_devices.xml, docs/opsguide/rdadmin.xml, docs/opsguide/rdairplay.xml, docs/opsguide/rdlibrary.xml, docs/opsguide/rivendell_filter.xml
For people like me that can't see the obvious.
=> (Master) Added text clarifying independent rdpanel(1) panels in Ops Guide.

ChangeLog, lib/librd_cs.ts, lib/librd_de.ts, lib/librd_es.ts, lib/librd_fr.ts, lib/librd_nb.ts, lib/librd_nn.ts, lib/librd_pt_BR.ts, lib/rdevent_line.cpp, lib/rdlog_event.cpp, lib/schedcartlist.cpp, rdlogmanager/generate_log.cpp, rdlogmanager/rdlogmanager_cs.ts, rdlogmanager/rdlogmanager_de.ts, rdlogmanager/rdlogmanager_es.ts, rdlogmanager/rdlogmanager_fr.ts, rdlogmanager/rdlogmanager_nb.ts, rdlogmanager/rdlogmanager_nn.ts, rdlogmanager/rdlogmanager_pt_BR.ts
Fixed regression in scheduler that caused events with two scheduler codes to fail.
Updated scheduler reports to indicate scheduler codes.
=> (Master Regression Fix) Fixed regression in scheduler and scheduler codes.

AUTHORS, ChangeLog, apis/pypad/scripts/Makefile.am, apis/pypad/scripts/pypad_xcmd.exemplar, apis/pypad/scripts/pypad_xcmd.py, apis/pypad/tests/Makefile.am, apis/pypad/tests/xcmd_server.py
Add ability to send PAD data to Pira.cz RDS encoders supporting the X-Command protocol.
=> (Master) Add pypad_xcmd.py PyPAD script for Pira.cz X-Command protocol

ChangeLog, rdlibrary/rdlibrary.cpp
=> (Master) Fixed a bug in rdlibrary(1) where double-clicking a cart would expand/collapse the item.

ChangeLog, rdlogmanager/list_events.cpp
=> Fixed bug in rdlogmanager(1) that could corrupt CLOCK_LINES table

ChangeLog, lib/rdevent_line.cpp, lib/rdschedcartlist.cpp
This replaces branch ```schedcodes_fix```.
=> (Master Bug) Fixed regression in scheduler when using two schedule codes.

ChangeLog, rdlibrary/rdlibrary.cpp
This is my proposed fix for #417
=> (Master Regression Fix) Fixed regression in rdlibrary(1) display when realtime filtering is disabled.

ChangeLog, lib/rdcart_dialog.cpp
=> (3.0.0rc02) Fixed bug in 'RDCartDialog' that caused an empty scheduler code dropdown box.

ChangeLog, rdlibrary/rdlibrary.cpp
=> (3.0.0rc02 Bug) Fixed bug in rdlibrary with matching carts count and color codes.

ChangeLog, lib/rdcut.cpp, lib/rdsvc.cpp, rdlibrary/list_reports.cpp, utils/rdclilogedit/operations.cpp, utils/rddbmgr/updateschema.cpp
=> Fix Several Typos That Cause SQL Errors

ChangeLog, rdairplay/loglinebox.cpp
Added support for dark themes.
=> Update loglinebox.cpp to support dark themes

ChangeLog, lib/rddropboxlistmodel.cpp, lib/rddropboxlistmodel.h, rdadmin/list_dropboxes.cpp
Fred, I followed your lead in the Group List dialog to sort the dropbox list by column headings.
=> Dropbox List in RDAdmin, sort list by column
