ElvishArtisan/rivendell

lib/rdedit_audio.cpp
lib/rdslotbox.cpp
lib/rdslotbox.h
rdairplay/list_log.cpp
rdairplay/list_log.h
rdairplay/loglinebox.cpp
rdairplay/loglinebox.h
rdairplay/post_counter.cpp
rdairplay/stop_counter.cpp
rdairplay/wall_clock.cpp
rdlibrary/audio_cart.cpp
rdlogedit/edit_log.cpp
rdlogedit/voice_tracker.cpp
rdlogmanager/edit_event.cpp

Rivendell has not worked with dark color themes from a factory install; RDAirplay has a fixed background on the log items but uses the system foreground color for text.
This patch modifies rivendell-2.10.1 to support dark themes, such as defaults with KXStudio. It also retains support for the original color theme that rivendell was developed for.
For example screen shots, please goto http://rivendell.danielbair.com/2014/11/30/rivendell-dark-theme-support/

Patches to add support for dark themes

---

lib/Makefile.am
lib/rdevent_line.cpp
lib/schedcart.cpp
lib/schedcart.h
lib/schedcartlist.cpp
lib/schedcartlist.h

We made some benchmarks on rdlogmanager log generation, to especially understand the reasons of the high CPU usage.
In fact ... the slowness is due to a bad choise of data structure in SchedCardList. It uses arrays and the item removal is very expensive, ... but it's the first usage 
This patch is refactoring SchedCardList by using a linked list of SchedCard objects.
The logic is the same, but the generation time has changed :
**Before :**
```
rdlogmanager -g -s Grille_A -d 1
441.38s user 0.31s system 94% cpu 7:48.03 total
```
**After :**
```
rdlogmanager -g -s Grille_A -d 1
10.08s user 0.22s system 29% cpu 34.661 total
```
It's 13x faster 
The patch contains 4 other commits to improve SQL queries performed by generateLog (which saves few seconds).
We tested this patch on several customer …

Schedcartlist without arrays

---

ChangeLog
lib/rdcae.cpp

If a file is missing in the /var/snd directory, the CAE daemon will send a "-1" value for stream. The lib/rdcae.cpp file does not check for that status and always returns true.  This causes RDAirplay to hang indefinitely when trying to play a track.
This patch checks for this status indicator and returns a false allowing RDAirplay to skip over the file and not have dead air.

Fix for missing files in /var/snd causing RDairplay to hang

---

ChangeLog
rdlibrary/rdlibrary.cpp

When searching in RDLibrary and selecting for 100 results of less, sometimes not all results are shown. This occurs when there are cuts or other items that may match the search term.  
A GROUP BY statement was added to the SQL to solve this issue.

Fix to rdlibrary.cpp to show all 100 carts in search when there are multiple matches in cuts

---

ChangeLog
lib/rdlog_event.cpp
lib/rdlog_event.h
lib/rdlog_line.cpp
lib/rdlog_line.h
rdlogedit/voice_tracker.cpp

Change from Alban Peignier's pull request #42 to speed up log saving to use a single SQL query.  In addition, a flag for voicetracker.cpp to require updates only when there is a change. 
This provides order of magnitude time saving over a network and permits remote voicetracking to work.  Without these changes, an "insert track" or "save" could take minutes.  Now, it is just a few seconds.

Refactored RDLogEvent::save() and voicetracker for substantial speed boost

---

ChangeLog
lib/rdcart.cpp

Favors cuts expiring first in weighted playback. This is useful when announcements are placed in a cart that have a near-term expiration date.

Favor soon-to-be-expiring cuts in weighted playback

---

lib/rdcartslot.cpp

GCC 6.1.1 defaults to `gnu++14` (C++14 with GNU extensions) as its default C++ standard. This leads to an ambiguity when calling `::abs`, since it can now take `int`, `long`, `long long`, or `__int128` (a GCC 128-bit wide integer type). Since the result of the expression `msecs-q->value(1).toInt()` is unsigned, the compiler must convert it back to a signed type before calling `::abs`.
Since it is assigned to an `int` later on anyway, the most sensible approach is to just assign the result of the expression to an `int` explicitly, which leaves no ambiguities when calling the function.

fix compilation with gcc 6.1.1

---

rdadmin/createdb.cpp
rdadmin/opendb.cpp

This converts opendb.cpp to standard create user and grant statements to fix the unable to connect to new db error you get when rdadmin has to create a new database from scratch.
This solves the incompatibilities with MySQL v5.7+ as password has been renamed to authentication string in the user table. I also used grant to apply the same database permissions as the original file, this should help guard against any other changes that might happen in the future.
This is compatible with earlier versions of MySQL for as far back as I can remember.
See issue #123 for more info.
This also fixes the rdairplay password prompts and the rdpanel segfault if you create a db from scratch.  This is because INSTANCE is a left over from before schema 219 and doesn't get removed as part of a new db, see …

Fixes for MySQL v5.7+ and db creation leftovers

---

importers/rivendell_filter.cpp
lib/rdcart.cpp
lib/rdcartslot.cpp
lib/rdcut.cpp
lib/rdescape_string.cpp
lib/rdescape_string.h
lib/rdevent_line.cpp
lib/rdfeed.cpp
lib/rdfeed.h
lib/rdlog.cpp
lib/rdlog_event.cpp
lib/rdpodcast.cpp
lib/rdpodcast.h
lib/rdrecording.cpp
lib/rdreport.cpp
lib/rdsound_panel.cpp
lib/rdsvc.cpp
rdairplay/log_traffic.cpp
rdcatchd/rdcatchd.cpp
tests/sas_switch_torture.cpp
tests/sas_torture.cpp
utils/rddgimport/rddgimport.cpp
utils/rdimport/rdimport.cpp
web/rdcastmanager/rdcastmanager.cpp

Pull request to resolve #121 date/time changes in MySQL v5.7+ for record insertion/updates.
I've done a lot of searching across the entirety of the Riv codebase for references to dates and times either as variable types or that reference database fields that are DATETIME (and variants).  I have the full 1,500 line matches file and the smaller 250 ish line file that I narrowed down after checking line by line.
I added a bunch of RDCheckDateTime methods to rdescape_string.cpp.  Most of the fixes revolve around finding where the original date/time/datetime is used and wrapping an isValid check around it that either returns a QString of the formatted date/time or "NULL" (not NULL a QString that says "NULL").
There is potential for some of the SELECT statements to suffer the same faults but …

MySQL v5.7+ Date/Time changes (RDCheckDateTime)

---

lib/rdtextvalidator.cpp

Previously, pressing backspace with a 1-character string blew up because pos=0, so pos-1=-1,
and strings of length zero always segfaulted because there are no characters to inspect.
Fixes #152 on Ubuntu 16.04 / Qt4.

Validate position within string we're being asked to validate

---

cae/cae_alsa.cpp
cae/cae_jack.cpp

There are several more bugs I don't really know the answer for.
Most are I suspect related to MySQL 5.7 security.
To setup the initial database, rdadmin must be run as root.
Then there are about a half dozen mysql errors while running the various rivendell applications, rdadmin, rdcatch, rdlogedit, rdlogmanager, rdpanel:
rdadmin
invalid SQL or failed DB connection[Field 'INSTANCE' doesn't have a default value QMYSQL3: Unable to execute query]: insert into RDPANEL set STATION="Rivendell-VirtualBox"
Database connection failed: insert into RDPANEL set STATION="Rivendell-VirtualBox"
QSqlQuery::value: not positioned on a valid record
invalid SQL or failed DB connection[Field 'PORT_2' doesn't have a default value QMYSQL3: Unable to execute query]: insert into MATRICES set …

Patches for building on Ubuntu 18.04

---

ChangeLog
utils/rdmaint/rdmaint.cpp
utils/rdmaint/rdmaint.h

The STACK only needs to reference as far back as needed to implement artist and title separation. This pull request looks at the artist and title separations to determine the number of carts to keep on the stack. The other carts are removed and the stack is renumbered.

Purge STACK tables in RDMaint

---

lib/rdedit_audio.cpp

Fixed regression with RDTransportButton and QPushButton events being lost
while cue edits and playback are active. I have no idea why/how this fixes
the problem.
When the buttons' focus policy is set to NoFocus with setFocusPolicy(Qt::NoFocus),
the problem of missing/dropped/lost events goes away.

(Master Bug Fix) "Fixed" a regression with RDTransportButton and QPushButton

---

ChangeLog
lib/rdsimpleplayer.cpp
rdlogedit/rdlogedit.cpp

Delete and Voice Track buttons were always enabled after selecting a log regardless of user authorization.

(Master Bug Fix) Fixed delete and voice track buttons in RDLogEdit

---

ChangeLog
lib/rdedit_audio.cpp

This fixes marker not erasing properly upon remove.

(Master Bug) Fixed erase marker error in the 'Edit Audio' dialog.

---

ChangeLog
lib/rdevent_line.cpp
lib/schedcartlist.cpp
lib/schedcartlist.h

Also fixed some formatting...
One issue to consider. One reason for moving a cart's schedule codes to its own table was to remove the 255 character limit (23 codes). Unfortunately, scheduler codes are stored in the stack in the same, old format with a maximum of 255 characters.

(Regression) Fixes clock scheduler rules in rdlogmanager(1) scheduler

---

ChangeLog
lib/rdschedruleslist.cpp
rdlogmanager/edit_schedcoderules.cpp

Fixed bug in clock schedule rules where "or After" schedule code were not displayed correctly.

(Master Bug) Fixed bug in rdlogmanager(1) scheduler rules

---

ChangeLog
utils/rdsoftkeys/rdsoftkeys.cpp

If now softkey definitions are found in the specified map file, rdsoftkeys(1) will display and error dialog and exit gracefully.
Addresses issue #427

(3.0.0rc02) Add error dialog to rdsoftkeys(1)

---

ChangeLog
lib/rdevent_line.cpp

There was a bug where the scheduler was restoring excluded carts when it wasn't supposed to. I believe this problem also exists in 2.19.

(3.0.0rc02 Bug) Fixed bug in rdlogmanager(1) deconflicting rules.

---

ChangeLog
lib/rdwavefile.cpp

> When a QFile is opened using this function, behaviour of close() is controlled by the ```handleFlags``` argument.  If ```AutoCloseHandle``` is specified, and this function succeeds, then calling close() closes the adopted handle.  Otherwise, close() does not actually close the file, but only flushes it.

(3.0.0rc02 Bug) Fixed bug in RDWaveFile that exhaused file handles.

---

ChangeLog
docs/manpages/rddbmgr.xml
utils/rddbmgr/check.cpp
utils/rddbmgr/rddbmgr.cpp
utils/rddbmgr/rddbmgr.h

I have several remote workstations and move files around using ```rsync```. I needed a way to only check for orphaned files on these remote workstations.

(3.0.0rc02 Feature) Added new '--orphaned-*' command line switches to rddbmgr(8).

---

ChangeLog
lib/rdwavefile.cpp

In AudioVAULT, the length of the SEC tone does not affect how long the segue lasts.   This should be reflected when importing audio files from AV.
I've had to go into the database and move the segue end markers to the end of the audio every time I've imported a library from AudioVAULT.
This pull requests sets the segue end marker to the end of the audio when importing audio from AV.

Disregard offset in Segue marker when importing AudioVAULT files.

---

ChangeLog
lib/rdlog_line.cpp

It appears to me as if this was left out of the changes introduced in commit 6eee8cb.
This PR fixes #548

Set log_cut_number in RDLogLine::loadCart().

---

ChangeLog
rdlogmanager/edit_event.cpp

Fixed a bug in rdlogmanager(1) that caused 'Make Post Point' label to be displayed without last 't'.

---

ChangeLog
rdairplay/hourselector.cpp

The timer was not set properly when crossing midnight. Fixes #552

Fixed a bug in rdairplay(1) with HourSelector::updateTimeData()

---

ChangeLog
rdairplay/list_log.cpp

Modified rdairplay(1) to always scroll log to the top when using the hour selector.

---

ChangeLog
rdlogmanager/generate_log.cpp

Disable merge buttons if the selected log does not contain any import links. Fixes #557

Modified rdlogmanager(1) to disable merge buttons

---

ChangeLog
rdadmin/list_dropboxes.cpp

It seems as if this has been broken for a long time. The values in the Path column has been centered for as long as I can recall. I finally looked at the code and the column numbers included two references to column Zero (0).
Also, I compiled the code with `Qt::AlignVCenter` OR'd in and it didn't seem to obey horizontal alignment. DId I do it wrong?
Thanks for considering this PR!

Correct column settings in Dropbox list view.

---

ChangeLog
lib/rddelete.cpp
lib/rddownload.cpp
lib/rdupload.cpp
rdcatch/edit_download.cpp
rdcatch/edit_upload.cpp

cURL supports 'ftps://' URLs so this change was trivial.
I have tested FTPS download (`rdcatch`), upload (`rdcastmanager`), and delete (rdcastmanger`). All are working with the FTPS server at nxx.grunch.org. FTP server log available on request...

Add support for FTPS upload and download in RDCatch.

---

ChangeLog
docs/tables/stack_lines.txt
lib/dbversion.h
lib/rdevent_line.cpp
lib/rdschedcartlist.cpp
lib/rdschedcartlist.h
utils/rddbmgr/rddbmgr.h
utils/rddbmgr/revertschema.cpp
utils/rddbmgr/schemamap.cpp
utils/rddbmgr/updateschema.cpp

Added a 'STACK_LINES.TITLE' field to the database.
Incremented the database version to 347.
Fixes #634

Fixed title separation in rdlogmanager(1) scheduler.

---

AUTHORS
ChangeLog
lib/rdwavefile.cpp

QStrings, like C strings end with "0", so
stop when reaching the first instance of 0.
fixes #636 
Signed-off-by: David Klann <dklann@broadcasttool.com>

Be less 'greedy' copying CartChunk Cut ID data.

---

ChangeLog
apis/pypad/scripts/pypad_ino713_tcp.exemplar
apis/pypad/scripts/pypad_ino713_tcp.py
apis/pypad/scripts/pypad_nautel.exemplar
apis/pypad/scripts/pypad_nautel.py

Created pypad_ino713_tcp based upon pypad_ino713, converting from UDP to TCP.  Added an adjustable delay to account for broadcast air delays.  
Created pypad_nautel based upon pypad_ino713_tcp, including RDS parameters from documentation.  Includes delay.

pypad scripts for Inovonics 713 TCP and Nautel

---

ChangeLog
conf/rd.conf-sample
lib/rd.h
lib/rdcae.cpp
lib/rdcae.h
lib/rdconfig.cpp
lib/rdconfig.h
systemd/rivendell.service.in

Parameterize values used for allocating the UDP port number for VU meters.
Fixes Issue #650 
Signed-off-by: David Klann <dklann@broadcasttool.com>

VU Meters update.

---

lib/rdwavepainter.cpp

On ARM, the unsigned cast seems to be respected; on x64, apparently not. 
In RDLogEdit's Voice Tracker, this causes incorrect waveform display on ARM systems (https://github.com/ElvishArtisan/rivendell/issues/389) - `startmsecs` can be negative when the start of the clip is to the right of X=0 (normal for the middle and bottom tracks).

Fix drawWaveByMsecs when startmsecs or endmsecs are negative

---

AUTHORS
ChangeLog
apis/pypad/api/pypad.py

Hello
When using pypad_udp.py, the pypad instance crashed complaining about undefined pypad object. This pull requests fixes this issue
Regards
Florent

Fix undefined symbol when using ProcessNullUpdates in configuration file
